spring:
  application:
    name: server-conversion

  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/Projects/distributed-system-umbrella/config
          clone-on-start: true
          search-paths: "*, dev, prod"