spring:
  application:
    name: server-config

  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/Projects/distributed-system-umbrella/config
          clone-on-start: true
          search-paths: *, {application}, config/{application}, config/, config/*